BINARY := MagicTheGatheRIIng

DOCKER_IMAGE := mtg
DOCKER_PORTS := 22002
DOCKER_CHALLENGE_NAME := $(BINARY)
DOCKER_CHALLENGE_PATH := $(DIR)/$(BINARY)
DOCKER_TIMELIMIT := 600
DOCKER_BUILD_ARGS := --build-arg "DIR=$(DIR)"
DOCKER_BUILD_DEPS := $(DIR)/pwnableserver $(DIR)/libpwnableharness64.so

PUBLISH_LIBC := $(BINARY)-libc.so
PUBLISH := $(BINARY)
